- name: ak_riks
  active: true
  mapping:
    location_county: LANSNAMN
    location_municipality: KOMMUNNAMN

- name: Havsomr_SVAR_2016_3b_CP1252
  active: true
  mapping:
    location_nation: Country
    # location_county:
    # location_municipality:
    location_water_district: District
    # location_svar_sea_area_code=,
    # location_svar_sea_area_name=,
    # location_water_category=,
    location_type_area: TYPOMRNAMN
    # location_helcom_ospar_area=,
    # location_economic_zone=,
    location_sea_basin: BASIN_NR

- name: KONVENTION
  active: true
  mapping:
    location_helcom_ospar_area: KONVENTION